// <auto-generated />
using System;
using Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab.Data.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20210524195816_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab.Model.CdiscTestCd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("CdiscTestCds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HGB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HCT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RBC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CA"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CdiscTestCdId")
                        .HasColumnType("int");

                    b.Property<int?>("CdiscTestId")
                        .HasColumnType("int");

                    b.Property<int>("Specimen")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CdiscTestCdId");

                    b.HasIndex("UnitId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Specimen = 0,
                            TestName = "Hemoglobin"
                        },
                        new
                        {
                            Id = 2,
                            Specimen = 0,
                            TestName = "Hematocrit"
                        },
                        new
                        {
                            Id = 3,
                            Specimen = 0,
                            TestName = "Red Blood Cell Count"
                        },
                        new
                        {
                            Id = 4,
                            Specimen = 1,
                            TestName = "Calcium"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTestRefRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LLN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("ULN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabTestRefRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LLN = "12.5",
                            LabTestId = 1,
                            Sex = 0,
                            ULN = "17.0"
                        });
                });

            modelBuilder.Entity("Lab.Model.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "10^6 cell/uL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mg/dL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "%"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ng/dL"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTest", b =>
                {
                    b.HasOne("Lab.Model.CdiscTestCd", "CdiscTestCd")
                        .WithMany()
                        .HasForeignKey("CdiscTestCdId");

                    b.HasOne("Lab.Model.Unit", "LabTestUnit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Lab.Model.LabTestRefRange", b =>
                {
                    b.HasOne("Lab.Model.LabTest", "LabTest")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
