// <auto-generated />
using System;
using Lab.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab.Data.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20210526025815_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab.Model.CdiscTestCd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("CdiscTestCds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HGB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HCT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PROT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CA"
                        });
                });

            modelBuilder.Entity("Lab.Model.CdiscTestName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("CdiscTest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hemoglobin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hematocrit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Protein"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Calcium"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CdiscTestCdId")
                        .HasColumnType("int");

                    b.Property<int?>("CdiscTestId")
                        .HasColumnType("int");

                    b.Property<int?>("CdiscTestNameId")
                        .HasColumnType("int");

                    b.Property<int>("Specimen")
                        .HasColumnType("int");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CdiscTestCdId");

                    b.HasIndex("CdiscTestNameId");

                    b.HasIndex("UnitId");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Specimen = 0,
                            TestName = "Hemoglobin"
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Specimen = 0,
                            TestName = "Hematocrit"
                        },
                        new
                        {
                            Id = 3,
                            Category = 5,
                            Specimen = 3,
                            TestName = "Urine Protein"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Specimen = 1,
                            TestName = "Calcium (Non-Ionized)"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTestConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConFac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("UnitFromId")
                        .HasColumnType("int");

                    b.Property<int>("UnitToId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("UnitFromId");

                    b.HasIndex("UnitToId");

                    b.ToTable("LabTestConversions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConFac = "100",
                            LabTestId = 1,
                            UnitFromId = 1,
                            UnitToId = 2
                        },
                        new
                        {
                            Id = 2,
                            ConFac = "10",
                            LabTestId = 1,
                            UnitFromId = 1,
                            UnitToId = 6
                        },
                        new
                        {
                            Id = 3,
                            ConFac = "100",
                            LabTestId = 3,
                            UnitFromId = 1,
                            UnitToId = 2
                        },
                        new
                        {
                            Id = 4,
                            ConFac = "10",
                            LabTestId = 3,
                            UnitFromId = 1,
                            UnitToId = 6
                        },
                        new
                        {
                            Id = 5,
                            ConFac = ".25",
                            LabTestId = 4,
                            UnitFromId = 5,
                            UnitToId = 2
                        },
                        new
                        {
                            Id = 6,
                            ConFac = "2.5",
                            LabTestId = 4,
                            UnitFromId = 5,
                            UnitToId = 6
                        },
                        new
                        {
                            Id = 7,
                            ConFac = "10",
                            LabTestId = 4,
                            UnitFromId = 1,
                            UnitToId = 6
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTestRefRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LLN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<string>("ULN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.ToTable("LabTestRefRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LLN = "11.5",
                            LabTestId = 1,
                            Sex = 1,
                            ULN = "15.0"
                        },
                        new
                        {
                            Id = 2,
                            LLN = "10",
                            LabTestId = 1,
                            Sex = 2,
                            ULN = "14.0"
                        },
                        new
                        {
                            Id = 3,
                            LLN = "35",
                            LabTestId = 2,
                            Sex = 1,
                            ULN = "45"
                        },
                        new
                        {
                            Id = 4,
                            LLN = "33",
                            LabTestId = 2,
                            Sex = 2,
                            ULN = "43"
                        },
                        new
                        {
                            Id = 5,
                            LLN = "5",
                            LabTestId = 3,
                            Sex = 2,
                            ULN = "25"
                        },
                        new
                        {
                            Id = 6,
                            LLN = "5",
                            LabTestId = 3,
                            Sex = 1,
                            ULN = "24"
                        },
                        new
                        {
                            Id = 7,
                            LLN = "8.5",
                            LabTestId = 4,
                            Sex = 0,
                            ULN = "10.5"
                        });
                });

            modelBuilder.Entity("Lab.Model.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "g/L"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mg/dL"
                        },
                        new
                        {
                            Id = 3,
                            Name = "%"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ng/dL"
                        },
                        new
                        {
                            Id = 5,
                            Name = "mmol/L"
                        },
                        new
                        {
                            Id = 6,
                            Name = "g/dL"
                        });
                });

            modelBuilder.Entity("Lab.Model.LabTest", b =>
                {
                    b.HasOne("Lab.Model.CdiscTestCd", "CdiscTestCd")
                        .WithMany()
                        .HasForeignKey("CdiscTestCdId");

                    b.HasOne("Lab.Model.CdiscTestName", "CdiscTestName")
                        .WithMany()
                        .HasForeignKey("CdiscTestNameId");

                    b.HasOne("Lab.Model.Unit", "LabTestUnit")
                        .WithMany()
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("Lab.Model.LabTestConversion", b =>
                {
                    b.HasOne("Lab.Model.LabTest", "LabTest")
                        .WithMany("Conversions")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab.Model.Unit", "UnitFrom")
                        .WithMany()
                        .HasForeignKey("UnitFromId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lab.Model.Unit", "UnitTo")
                        .WithMany()
                        .HasForeignKey("UnitToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab.Model.LabTestRefRange", b =>
                {
                    b.HasOne("Lab.Model.LabTest", "LabTest")
                        .WithMany("ReferenceRanges")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
